disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - force_cast
  - large_tuple
  - notification_center_detachment
  - nesting
  - function_parameter_count
  - trailing_whitespace
opt_in_rules: # some rules are only opt-in
  - empty_count
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - fastlane
  - Gemfile
  - Gemfile.lock
  - README.md
line_length:
  warning: 160
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
